from __future__ import annotations

import json
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal


DEFAULT_INPUT = Path("methods.json")
DEFAULT_GENERATED_OUTPUT = Path("generated-docs.json")
DEFAULT_PAGES_DIR = Path("docs")
DEFAULT_INDEX_LINK = "index.md"
DEFAULT_REPORT = Path("docs-generation-report.json")
DEFAULT_ENV_FILE = Path("tools/.env")
DEFAULT_MODEL = "gpt-5.5"
DEFAULT_SEED = 613
ReasoningEffort = Literal["none", "minimal", "low", "medium", "high", "xhigh"]
DEFAULT_REASONING_EFFORT: ReasoningEffort = "low"
GENERATED_MARKER = "<!-- Generated by tools/generate-md.py. Do not edit by hand. -->"


@dataclass(frozen=True)
class SourceEntry:
    id: str
    title: str
    method: str
    class_name: str
    qualified_name: str
    source_file: str
    line: int | None
    is_deprecated: bool
    raw_javadoc: str
    category: str


def load_json(path: Path) -> tuple[list[dict[str, Any]], str]:
    errors: list[str] = []
    for encoding in ("utf-8-sig", "utf-16", "utf-16-le", "utf-16-be"):
        try:
            data = json.loads(path.read_text(encoding=encoding))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            errors.append(f"{encoding}: {exc}")
            continue

        if not isinstance(data, list):
            raise ValueError(f"Expected a JSON list in {path}")
        return data, encoding

    raise ValueError(f"Could not decode {path} as JSON. Tried: {'; '.join(errors)}")


def split_camel_case(value: str) -> str:
    value = re.sub(r"^get", "", value)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", value)
    value = re.sub(r"([A-Za-z])([0-9])", r"\1 \2", value)
    value = re.sub(r"([0-9])([A-Za-z])", r"\1 \2", value)
    return re.sub(r"\s+", " ", value).strip()


def entry_title(method: str) -> str:
    return split_camel_case(method)


def category_for(item: dict[str, Any]) -> str:
    method = str(item.get("name", ""))
    qualified_name = str(item.get("qualified_name") or method)
    category_id = ZMAN_CATEGORIES.get(method) or ZMAN_CATEGORIES.get(qualified_name)

    if category_id is None:
        raise ValueError(
            f"No category configured for {qualified_name}. "
            "Add it to ZMAN_CATEGORIES in tools/zman_categories.py or EXCLUDED_ZMANIM."
        )
    if category_id not in CATEGORY_LABELS:
        raise ValueError(
            f"Unknown category {category_id!r} configured for {qualified_name}. "
            "Add it to CATEGORY_LABELS in tools/zman_categories.py."
        )
    return CATEGORY_LABELS[category_id]


def entry_rank(entry: SourceEntry) -> tuple[int, int]:
    if entry.class_name == "ComprehensiveZmanimCalendar":
        return (0, 0)
    if entry.class_name == "ZmanimCalendar":
        return (1, 0)
    if entry.class_name == "AstronomicalCalendar":
        return (2, 0)
    if entry.class_name == "JewishCalendar":
        return (3, 0)
    return (4, 0)


def deduplicate_entries(entries: list[SourceEntry]) -> list[SourceEntry]:
    by_title_category: dict[tuple[str, str], SourceEntry] = {}
    for entry in entries:
        key = (entry.category, entry.title)
        existing = by_title_category.get(key)
        if existing is None or entry_rank(entry) < entry_rank(existing):
            by_title_category[key] = entry
    return list(by_title_category.values())


def source_entries(items: list[dict[str, Any]]) -> list[SourceEntry]:
    entries: list[SourceEntry] = []

    for index, item in enumerate(items):
        raw_docs = item.get("docs")
        docs: dict[str, Any] = raw_docs if isinstance(raw_docs, dict) else {}
        raw_javadoc = str(docs.get("raw") or "").strip()
        method = str(item.get("name") or f"item_{index}")
        qualified_name = str(item.get("qualified_name") or method)
        if method in EXCLUDED_ZMANIM or qualified_name in EXCLUDED_ZMANIM:
            continue

        entries.append(
            SourceEntry(
                id=qualified_name,
                title=entry_title(method),
                method=method,
                class_name=str(item.get("class") or ""),
                qualified_name=qualified_name,
                source_file=str(item.get("file") or ""),
                line=item.get("line") if isinstance(item.get("line"), int) else None,
                is_deprecated=bool(item.get("is_deprecated")),
                raw_javadoc=raw_javadoc,
                category=category_for(item),
            )
        )

    return deduplicate_entries(entries)


def category_sort_key(category: str) -> tuple[int, str]:
    ordered_labels = [
        CATEGORY_LABELS[category_id]
        for category_id in CATEGORY_ORDER
        if category_id in CATEGORY_LABELS
    ]
    try:
        return (ordered_labels.index(category), category)
    except ValueError:
        return (len(ordered_labels), category)


def validate_category_config() -> None:
    unknown_order = [
        category_id
        for category_id in CATEGORY_ORDER
        if category_id not in CATEGORY_LABELS
    ]
    unknown_assignments = sorted(set(ZMAN_CATEGORIES.values()) - set(CATEGORY_LABELS))

    errors: list[str] = []
    if unknown_order:
        errors.append(
            f"Unknown category ids in CATEGORY_ORDER: {', '.join(unknown_order)}"
        )
    if unknown_assignments:
        errors.append(
            "Unknown category ids in ZMAN_CATEGORIES: " + ", ".join(unknown_assignments)
        )
    if errors:
        raise ValueError(
            "Invalid category configuration in tools/zman_categories.py. "
            + " ".join(errors)
        )


def grouped_entries(entries: list[SourceEntry]) -> dict[str, list[SourceEntry]]:
    groups: dict[str, list[SourceEntry]] = defaultdict(list)
    for entry in entries:
        groups[entry.category].append(entry)

    for category_entries in groups.values():
        category_entries.sort(key=lambda item: (item.class_name, item.method, item.id))

    return dict(sorted(groups.items(), key=lambda pair: category_sort_key(pair[0])))


def base_report(
    command: str,
    input_path: Path,
    generated_content: str,
    pages_dir: str,
    index_link: str,
    model: str | None,
    seed: int | None,
    reasoning_effort: str | None,
    dry_run: bool,
    encoding: str,
    source_count: int,
    entries: list[SourceEntry],
    groups: dict[str, list[SourceEntry]],
) -> dict[str, Any]:
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "command": command,
        "input": str(input_path),
        "generated_content": generated_content,
        "pages_dir": pages_dir,
        "index_link": index_link,
        "model": model,
        "seed": seed,
        "reasoning_effort": reasoning_effort,
        "dry_run": dry_run,
        "source_encoding": encoding,
        "source_entries": source_count,
        "render_entries": len(entries),
        "categories": {
            category: len(category_entries)
            for category, category_entries in groups.items()
        },
        "generated_items": 0,
        "skipped_items": [],
        "warnings": [],
    }


def add_missing_raw_skips(report: dict[str, Any], entries: list[SourceEntry]) -> None:
    for entry in entries:
        if not entry.raw_javadoc:
            report["skipped_items"].append(
                {
                    "id": entry.id,
                    "title": entry.title,
                    "reason": "No docs.raw Javadoc text was available.",
                }
            )


def print_category_summary(
    items: list[dict[str, Any]],
    entries: list[SourceEntry],
    groups: dict[str, list[SourceEntry]],
) -> None:
    print(f"Loaded {len(items)} source entries as {len(entries)} render entries.")
    for category, category_entries in groups.items():
        print(f"{category}: {len(category_entries)}")


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True) if path.parent != Path(".") else None
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


"""Editable category assignments for generated zmanim docs.

Edit CATEGORY_LABELS to rename a category.
Edit CATEGORY_ORDER to reorder categories.
Edit ZMAN_CATEGORIES to move a zman to a different category.

Every generated zman must be listed in ZMAN_CATEGORIES unless it is listed in
EXCLUDED_ZMANIM. Missing or unknown category assignments are treated as errors.
"""

CATEGORY_LABELS = {
    "alos": "Alos HaShachar",
    "astronomical_dawn": "Astronomical Dawn",
    "mishayakir": "Misheyakir",
    "sunrise": "Netz",
    "end_shema": "Sof Zman Shema",
    "end_tefilla": "Sof Zman Tefilla",
    "end_eating_chometz": "Sof Zman Achilas Chametz",
    "end_burning_chometz": "Sof Zman Biur Chametz",
    "midday": "Chatzos Hayom",
    "mincha_gedola": "Mincha Gedola",
    "mincha_ketana": "Mincha Ketana",
    "plag_mincha": "Plag Mincha",
    "sunset": "Shkiah",
    "astronomical_twilight": "Astronomical Twilight",
    "midnight": "Midnight",
    "bein_hashmashos": "Bein Hashmashos",
    "tzais_geonim": "Tzais (Geonim)",
    "tzais": "Tzais (Rabbeinu Tam)",
    "kidush_levana": "Kidush Levana",
    "candle_lighting": "Candle Lighting",
}

CATEGORY_ORDER = [
    "alos",
    "astronomical_dawn",
    "mishayakir",
    "sunrise",
    "end_shema",
    "end_tefilla",
    "end_eating_chometz",
    "end_burning_chometz",
    "midday",
    "mincha_gedola",
    "mincha_ketana",
    "plag_mincha",
    "candle_lighting",
    "sunset",
    "bein_hashmashos",
    "tzais_geonim",
    "tzais",
    "astronomical_twilight",
    "midnight",
    "kidush_levana",
]

EXCLUDED_ZMANIM = {"getZman", "getMoladAsInstant", "getZmanMolad"}

ZMAN_CATEGORIES = {
    "getSunrise": "sunrise",
    "getSeaLevelSunrise": "sunrise",
    "getBeginCivilTwilight": "astronomical_dawn",
    "getBeginNauticalTwilight": "astronomical_dawn",
    "getBeginAstronomicalTwilight": "astronomical_dawn",
    "getSunset": "sunset",
    "getSeaLevelSunset": "sunset",
    "getEndCivilTwilight": "astronomical_twilight",
    "getEndNauticalTwilight": "astronomical_twilight",
    "getEndAstronomicalTwilight": "astronomical_twilight",
    "getSunTransit": "midday",
    "getSolarMidnight": "midnight",
    "getPlagHamincha120MinutesZmanis": "plag_mincha",
    "getPlagHamincha120Minutes": "plag_mincha",
    "getAlos60Minutes": "alos",
    "getAlos72Zmanis": "alos",
    "getAlos96Minutes": "alos",
    "getAlos90Zmanis": "alos",
    "getAlos96Zmanis": "alos",
    "getAlos90Minutes": "alos",
    "getAlos120Minutes": "alos",
    "getAlos120Zmanis": "alos",
    "getAlos26Degrees": "alos",
    "getAlos18Degrees": "alos",
    "getAlos19Degrees": "alos",
    "getAlos19Point8Degrees": "alos",
    "getMisheyakir12Point85Degrees": "mishayakir",
    "getMisheyakir11Point5Degrees": "mishayakir",
    "getMisheyakir11Degrees": "mishayakir",
    "getMisheyakir10Point2Degrees": "mishayakir",
    "getMisheyakir7Point65Degrees": "mishayakir",
    "getMisheyakir9Point5Degrees": "mishayakir",
    "getSofZmanShmaMGA19Point8Degrees": "end_shema",
    "getSofZmanShmaMGA16Point1Degrees": "end_shema",
    "getSofZmanShmaMGA18Degrees": "end_shema",
    "getSofZmanShmaMGA72MinutesZmanis": "end_shema",
    "getSofZmanShmaMGA90Minutes": "end_shema",
    "getSofZmanShmaMGA90MinutesZmanis": "end_shema",
    "getSofZmanShmaMGA96Minutes": "end_shema",
    "getSofZmanShmaMGA96MinutesZmanis": "end_shema",
    "getSofZmanShma3HoursBeforeChatzos": "end_shema",
    "getSofZmanShmaMGA120Minutes": "end_shema",
    "getSofZmanShmaAlos16Point1ToSunset": "end_shema",
    "getSofZmanShmaAlos16Point1ToTzaisGeonim7Point083Degrees": "end_shema",
    "getSofZmanTfilaMGA19Point8Degrees": "end_tefilla",
    "getSofZmanTfilaMGA16Point1Degrees": "end_tefilla",
    "getSofZmanTfilaMGA18Degrees": "end_tefilla",
    "getSofZmanTfilaMGA72MinutesZmanis": "end_tefilla",
    "getSofZmanTfilaMGA90Minutes": "end_tefilla",
    "getSofZmanTfilaMGA90MinutesZmanis": "end_tefilla",
    "getSofZmanTfilaMGA96Minutes": "end_tefilla",
    "getSofZmanTfilaMGA96MinutesZmanis": "end_tefilla",
    "getSofZmanTfilaMGA120Minutes": "end_tefilla",
    "getSofZmanTfila2HoursBeforeChatzos": "end_tefilla",
    "getMinchaGedola30Minutes": "mincha_gedola",
    "getMinchaGedola72Minutes": "mincha_gedola",
    "getMinchaGedola16Point1Degrees": "mincha_gedola",
    "getMinchaGedolaAhavatShalom": "mincha_gedola",
    "getMinchaGedolaGRAGreaterThan30": "mincha_gedola",
    "getMinchaKetana16Point1Degrees": "mincha_ketana",
    "getMinchaKetanaAhavatShalom": "mincha_ketana",
    "getMinchaKetana72Minutes": "mincha_ketana",
    "getPlagHamincha60Minutes": "plag_mincha",
    "getPlagHamincha72Minutes": "plag_mincha",
    "getPlagHamincha90Minutes": "plag_mincha",
    "getPlagHamincha96Minutes": "plag_mincha",
    "getPlagHamincha96MinutesZmanis": "plag_mincha",
    "getPlagHamincha90MinutesZmanis": "plag_mincha",
    "getPlagHamincha72MinutesZmanis": "plag_mincha",
    "getPlagHamincha16Point1Degrees": "plag_mincha",
    "getPlagHamincha19Point8Degrees": "plag_mincha",
    "getPlagHamincha26Degrees": "plag_mincha",
    "getPlagHamincha18Degrees": "plag_mincha",
    "getPlagAlosToSunset": "plag_mincha",
    "getPlagAlos16Point1ToTzaisGeonim7Point083Degrees": "plag_mincha",
    "getPlagAhavatShalom": "plag_mincha",
    "getBainHashmashosRT13Point24Degrees": "bein_hashmashos",
    "getBainHashmashosRT58Point5Minutes": "bein_hashmashos",
    "getBainHashmashosRT13Point5MinutesBefore7Point083Degrees": "bein_hashmashos",
    "getBainHashmashosRT2Stars": "bein_hashmashos",
    "getBainHashmashosYereim18Minutes": "bein_hashmashos",
    "getBainHashmashosYereim3Point05Degrees": "bein_hashmashos",
    "getBainHashmashosYereim16Point875Minutes": "bein_hashmashos",
    "getBainHashmashosYereim2Point8Degrees": "bein_hashmashos",
    "getBainHashmashosYereim13Point5Minutes": "bein_hashmashos",
    "getBainHashmashosYereim2Point1Degrees": "bein_hashmashos",
    "getTzaisGeonim3Point7Degrees": "tzais_geonim",
    "getTzaisGeonim3Point8Degrees": "tzais_geonim",
    "getTzaisGeonim5Point95Degrees": "tzais_geonim",
    "getTzaisGeonim4Point66Degrees": "tzais_geonim",
    "getTzaisGeonim4Point42Degrees": "tzais_geonim",
    "getTzaisGeonim4Point8Degrees": "tzais_geonim",
    "getTzaisGeonim6Point45Degrees": "tzais_geonim",
    "getTzaisGeonim7Point083Degrees": "tzais_geonim",
    "getTzaisGeonim7Point67Degrees": "tzais_geonim",
    "getTzaisGeonim9Point3Degrees": "tzais_geonim",
    "getTzaisGeonim9Point75Degrees": "tzais_geonim",
    "getTzais60Minutes": "tzais",
    "getTzaisAteretTorah": "tzais",
    "getSofZmanShmaAteretTorah": "end_shema",
    "getSofZmanTfilaAteretTorah": "end_tefilla",
    "getMinchaGedolaAteretTorah": "mincha_gedola",
    "getMinchaKetanaAteretTorah": "mincha_ketana",
    "getPlagHaminchaAteretTorah": "plag_mincha",
    "getTzais72Zmanis": "tzais",
    "getTzais90Zmanis": "tzais",
    "getTzais96Zmanis": "tzais",
    "getTzais90Minutes": "tzais",
    "getTzais120Minutes": "tzais",
    "getTzais120Zmanis": "tzais",
    "getTzais16Point1Degrees": "tzais",
    "getTzais26Degrees": "tzais",
    "getTzais18Degrees": "tzais",
    "getTzais19Point8Degrees": "tzais",
    "getTzais96Minutes": "tzais",
    "getFixedLocalChatzosHayom": "midday",
    "getSofZmanKidushLevanaBetweenMoldos": "kidush_levana",
    "getSofZmanKidushLevana15Days": "kidush_levana",
    "getTchilasZmanKidushLevana3Days": "kidush_levana",
    "getTchilasZmanKidushLevana7Days": "kidush_levana",
    "getSofZmanAchilasChametzGRA": "end_eating_chometz",
    "getSofZmanAchilasChametzMGA72Minutes": "end_eating_chometz",
    "getSofZmanAchilasChametzMGA72MinutesZmanis": "end_eating_chometz",
    "getSofZmanAchilasChametzMGA16Point1Degrees": "end_eating_chometz",
    "getSofZmanBiurChametzGRA": "end_burning_chometz",
    "getSofZmanBiurChametzMGA72Minutes": "end_burning_chometz",
    "getSofZmanBiurChametzMGA72MinutesZmanis": "end_burning_chometz",
    "getSofZmanBiurChametzMGA16Point1Degrees": "end_burning_chometz",
    "getAlosBaalHatanya": "alos",
    "getSofZmanShmaBaalHatanya": "end_shema",
    "getSofZmanTfilaBaalHatanya": "end_tefilla",
    "getSofZmanAchilasChametzBaalHatanya": "end_eating_chometz",
    "getSofZmanBiurChametzBaalHatanya": "end_burning_chometz",
    "getMinchaGedolaBaalHatanya": "mincha_gedola",
    "getMinchaKetanaBaalHatanya": "mincha_ketana",
    "getPlagHaminchaBaalHatanya": "plag_mincha",
    "getTzaisBaalHatanya": "tzais",
    "getSofZmanShmaMGA18DegreesToFixedLocalChatzos": "end_shema",
    "getSofZmanShmaMGA16Point1DegreesToFixedLocalChatzos": "end_shema",
    "getSofZmanShmaMGA90MinutesToFixedLocalChatzos": "end_shema",
    "getSofZmanShmaMGA72MinutesToFixedLocalChatzos": "end_shema",
    "getSofZmanShmaGRASunriseToFixedLocalChatzos": "end_shema",
    "getSofZmanTfilaGRASunriseToFixedLocalChatzos": "end_tefilla",
    "getMinchaGedolaGRAFixedLocalChatzos30Minutes": "mincha_gedola",
    "getMinchaKetanaGRAFixedLocalChatzosToSunset": "mincha_ketana",
    "getPlagHaminchaGRAFixedLocalChatzosToSunset": "plag_mincha",
    "getTzais50Minutes": "tzais",
    "getSamuchLeMinchaKetanaGRA": "mincha_ketana",
    "getSamuchLeMinchaKetana16Point1Degrees": "mincha_ketana",
    "getSamuchLeMinchaKetana72Minutes": "mincha_ketana",
    "getSunsetOrWesternmostSolarAzimuth": "sunset",
    "getSunriseOrEasternmostSolarAzimuth": "sunrise",
    "getTzaisGeonim8Point5Degrees": "tzais_geonim",
    "getAlos16Point1Degrees": "alos",
    "getAlos72Minutes": "alos",
    "getChatzosHayom": "midday",
    "getChatzosHalayla": "midnight",
    "getChatzosHayomAsHalfDay": "midday",
    "getSofZmanShmaGRA": "end_shema",
    "getSofZmanShmaMGA72Minutes": "end_shema",
    "getTzais72Minutes": "tzais",
    "getCandleLighting": "candle_lighting",
    "getSofZmanTfilaGRA": "end_tefilla",
    "getSofZmanTfilaMGA72Minutes": "end_tefilla",
    "getMinchaGedolaGRA": "mincha_gedola",
    "getMinchaKetanaGRA": "mincha_ketana",
    "getPlagHaminchaGRA": "plag_mincha",
}
