from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal, cast

from openai import AsyncOpenAI
from zman_categories import (
    CATEGORY_LABELS,
    CATEGORY_ORDER,
    EXCLUDED_ZMANIM,
    ZMAN_CATEGORIES,
)


DEFAULT_INPUT = Path("methods.json")
DEFAULT_GENERATED_OUTPUT = Path("generated-docs.json")
DEFAULT_PAGES_DIR = Path("docs")
DEFAULT_INDEX_LINK = "index.md"
OLD_GENERATED_PAGES_DIR = Path("docs/zmanim")
DEFAULT_REPORT = Path("docs-generation-report.json")
DEFAULT_ENV_FILE = Path("tools/.env")
DEFAULT_MODEL = "gpt-5.5"
DEFAULT_SEED = 613
ReasoningEffort = Literal["none", "minimal", "low", "medium", "high", "xhigh"]
DEFAULT_REASONING_EFFORT: ReasoningEffort = "low"
GENERATED_MARKER = "<!-- Generated by tools/generate-docs.py. Do not edit by hand. -->"


@dataclass(frozen=True)
class SourceEntry:
    id: str
    title: str
    method: str
    class_name: str
    qualified_name: str
    source_file: str
    line: int | None
    is_deprecated: bool
    raw_javadoc: str
    category: str


@dataclass(frozen=True)
class BatchJob:
    index: int
    category: str
    entries: list[SourceEntry]


@dataclass(frozen=True)
class BatchResult:
    job: BatchJob
    output: dict[str, dict[str, Any]]
    warnings: list[str]
    error: str | None = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate user-facing zmanim docs from raw Javadoc JSON.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate = subparsers.add_parser(
        "generate-json",
        help="Call GPT and write generated user-facing content to JSON.",
    )
    generate.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Parsed methods JSON to read (default: {DEFAULT_INPUT})",
    )
    generate.add_argument(
        "--generated-output",
        type=Path,
        default=DEFAULT_GENERATED_OUTPUT,
        help=f"Generated content JSON to write (default: {DEFAULT_GENERATED_OUTPUT})",
    )
    generate.add_argument(
        "--report",
        type=Path,
        default=DEFAULT_REPORT,
        help=f"Generation report JSON to write (default: {DEFAULT_REPORT})",
    )
    generate.add_argument(
        "--env-file",
        type=Path,
        default=DEFAULT_ENV_FILE,
        help=f"Optional env file with OPENAI-KEY or OPENAI_API_KEY (default: {DEFAULT_ENV_FILE})",
    )
    generate.add_argument(
        "--model",
        default=os.environ.get("OPENAI_MODEL", DEFAULT_MODEL),
        help=f"OpenAI model to use (default: OPENAI_MODEL or {DEFAULT_MODEL})",
    )
    generate.add_argument(
        "--batch-size",
        type=int,
        default=8,
        help="Number of zmanim to send to the model in each request.",
    )
    generate.add_argument(
        "--request-timeout",
        type=float,
        default=120.0,
        help="OpenAI request timeout in seconds.",
    )
    generate.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help=f"Seed to reuse for model generation (default: {DEFAULT_SEED}).",
    )
    generate.add_argument(
        "--reasoning-effort",
        choices=("none", "minimal", "low", "medium", "high", "xhigh"),
        default=DEFAULT_REASONING_EFFORT,
        help=f"Reasoning effort for GPT models that support it (default: {DEFAULT_REASONING_EFFORT}).",
    )
    generate.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate input, grouping, and prompt construction without calling OpenAI.",
    )

    render = subparsers.add_parser(
        "render-md",
        help="Render Markdown docs from previously generated JSON.",
    )
    render.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Parsed methods JSON to read (default: {DEFAULT_INPUT})",
    )
    render.add_argument(
        "--generated",
        type=Path,
        default=DEFAULT_GENERATED_OUTPUT,
        help=f"Generated content JSON to read (default: {DEFAULT_GENERATED_OUTPUT})",
    )
    render.add_argument(
        "--pages-dir",
        type=Path,
        default=DEFAULT_PAGES_DIR,
        help=f"Directory for generated category Markdown files (default: {DEFAULT_PAGES_DIR})",
    )
    render.add_argument(
        "--index-link",
        default=DEFAULT_INDEX_LINK,
        help=f"Back link target for generated category pages (default: {DEFAULT_INDEX_LINK})",
    )
    render.add_argument(
        "--report",
        type=Path,
        default=DEFAULT_REPORT,
        help=f"Generation report JSON to write (default: {DEFAULT_REPORT})",
    )
    render.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate generated content and Markdown page planning without writing docs.",
    )
    return parser.parse_args()


def load_env_values(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue

        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip().strip("\"'")
        if key:
            values[key] = value
    return values


def openai_api_key(env_file: Path) -> str | None:
    env_values = load_env_values(env_file)
    return (
        os.environ.get("OPENAI_API_KEY")
        or os.environ.get("OPENAI-KEY")
        or env_values.get("OPENAI_API_KEY")
        or env_values.get("OPENAI-KEY")
    )


def load_json(path: Path) -> tuple[list[dict[str, Any]], str]:
    errors: list[str] = []
    for encoding in ("utf-8-sig", "utf-16", "utf-16-le", "utf-16-be"):
        try:
            data = json.loads(path.read_text(encoding=encoding))
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            errors.append(f"{encoding}: {exc}")
            continue

        if not isinstance(data, list):
            raise ValueError(f"Expected a JSON list in {path}")
        return data, encoding

    raise ValueError(f"Could not decode {path} as JSON. Tried: {'; '.join(errors)}")


def split_camel_case(value: str) -> str:
    value = re.sub(r"^get", "", value)
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", value)
    value = re.sub(r"([A-Za-z])([0-9])", r"\1 \2", value)
    value = re.sub(r"([0-9])([A-Za-z])", r"\1 \2", value)
    return re.sub(r"\s+", " ", value).strip()


def entry_title(method: str) -> str:
    title = split_camel_case(method)
    return title


def category_for(item: dict[str, Any]) -> str:
    method = str(item.get("name", ""))
    qualified_name = str(item.get("qualified_name") or method)
    category_id = ZMAN_CATEGORIES.get(method) or ZMAN_CATEGORIES.get(qualified_name)

    if category_id is None:
        raise ValueError(
            f"No category configured for {qualified_name}. "
            "Add it to ZMAN_CATEGORIES in tools/zman_categories.py or EXCLUDED_ZMANIM."
        )
    if category_id not in CATEGORY_LABELS:
        raise ValueError(
            f"Unknown category {category_id!r} configured for {qualified_name}. "
            "Add it to CATEGORY_LABELS in tools/zman_categories.py."
        )
    return CATEGORY_LABELS[category_id]


def entry_rank(entry: SourceEntry) -> tuple[int, int]:
    if entry.class_name == "ComprehensiveZmanimCalendar":
        return (0, 0)
    if entry.class_name == "ZmanimCalendar":
        return (1, 0)
    if entry.class_name == "AstronomicalCalendar":
        return (2, 0)
    if entry.class_name == "JewishCalendar":
        return (3, 0)
    return (4, 0)


def deduplicate_entries(entries: list[SourceEntry]) -> list[SourceEntry]:
    by_title_category: dict[tuple[str, str], SourceEntry] = {}
    for entry in entries:
        key = (entry.category, entry.title)
        existing = by_title_category.get(key)
        if existing is None or entry_rank(entry) < entry_rank(existing):
            by_title_category[key] = entry
    return list(by_title_category.values())


def source_entries(items: list[dict[str, Any]]) -> list[SourceEntry]:
    entries: list[SourceEntry] = []

    for index, item in enumerate(items):
        raw_docs = item.get("docs")
        docs: dict[str, Any] = raw_docs if isinstance(raw_docs, dict) else {}
        raw_javadoc = str(docs.get("raw") or "").strip()
        method = str(item.get("name") or f"item_{index}")
        qualified_name = str(item.get("qualified_name") or method)
        if method in EXCLUDED_ZMANIM or qualified_name in EXCLUDED_ZMANIM:
            continue
        class_name = str(item.get("class") or "")
        source_file = str(item.get("file") or "")
        line = item.get("line") if isinstance(item.get("line"), int) else None
        is_deprecated = bool(item.get("is_deprecated"))
        category = category_for(item)

        if not raw_javadoc:
            entries.append(
                SourceEntry(
                    id=qualified_name,
                    title=entry_title(method),
                    method=method,
                    class_name=class_name,
                    qualified_name=qualified_name,
                    source_file=source_file,
                    line=line,
                    is_deprecated=is_deprecated,
                    raw_javadoc=raw_javadoc,
                    category=category,
                )
            )
            continue

        entries.append(
            SourceEntry(
                id=qualified_name,
                title=entry_title(method),
                method=method,
                class_name=class_name,
                qualified_name=qualified_name,
                source_file=source_file,
                line=line,
                is_deprecated=is_deprecated,
                raw_javadoc=raw_javadoc,
                category=category,
            )
        )

    return deduplicate_entries(entries)


def category_sort_key(category: str) -> tuple[int, str]:
    ordered_labels = [
        CATEGORY_LABELS[category_id]
        for category_id in CATEGORY_ORDER
        if category_id in CATEGORY_LABELS
    ]
    try:
        return (ordered_labels.index(category), category)
    except ValueError:
        return (len(ordered_labels), category)


def validate_category_config() -> None:
    unknown_order = [
        category_id
        for category_id in CATEGORY_ORDER
        if category_id not in CATEGORY_LABELS
    ]
    unknown_assignments = sorted(set(ZMAN_CATEGORIES.values()) - set(CATEGORY_LABELS))

    errors: list[str] = []
    if unknown_order:
        errors.append(
            f"Unknown category ids in CATEGORY_ORDER: {', '.join(unknown_order)}"
        )
    if unknown_assignments:
        errors.append(
            "Unknown category ids in ZMAN_CATEGORIES: " + ", ".join(unknown_assignments)
        )
    if errors:
        raise ValueError(
            "Invalid category configuration in tools/zman_categories.py. "
            + " ".join(errors)
        )


def grouped_entries(entries: list[SourceEntry]) -> dict[str, list[SourceEntry]]:
    groups: dict[str, list[SourceEntry]] = defaultdict(list)
    for entry in entries:
        groups[entry.category].append(entry)

    for category_entries in groups.values():
        category_entries.sort(key=lambda item: (item.class_name, item.method, item.id))

    return dict(sorted(groups.items(), key=lambda pair: category_sort_key(pair[0])))


def batched(entries: list[SourceEntry], batch_size: int) -> list[list[SourceEntry]]:
    if batch_size < 1:
        raise ValueError("--batch-size must be at least 1")
    return [
        entries[index : index + batch_size]
        for index in range(0, len(entries), batch_size)
    ]


def model_payload(entry: SourceEntry) -> dict[str, Any]:
    return {
        "id": entry.id,
        "title": entry.title,
        "method": entry.method,
        "class": entry.class_name,
        "is_deprecated": entry.is_deprecated,
        "raw_javadoc": entry.raw_javadoc,
    }


def system_prompt() -> str:
    return (
        "You turn raw Java Javadoc for KosherJava zmanim methods into concise, "
        "user-facing documentation for people trying to understand zmanim, not "
        "developers trying to use an API. You must be evidence-bound: use only facts "
        "directly supported by each item's raw_javadoc. Do not add halachic, "
        "astronomical, historical, API, or usage context unless it appears in "
        "raw_javadoc. Never mention Javadoc, source code, methods, APIs, return "
        "values, or Java concepts in user-facing fields. Translate developer terms "
        "into plain language: for example, do not say 'returns null'; say that the "
        "time may not be available or cannot be calculated in that situation. If "
        "raw_javadoc includes Javadoc inline links and HTML links; preserve useful "
        "user-facing links as Markdown when you use the linked text, but do not add "
        "links that are not present in the raw_javadoc. If the raw_javadoc does not "
        "support a field, return an empty string or an empty list for that field."
    )


def user_prompt(category: str, entries: list[SourceEntry]) -> str:
    payload = {
        "category": category,
        "requirements": [
            "Return valid JSON only.",
            "Return one output item for every input id.",
            "Do not include markdown headings in fields.",
            "Write fields as plain paragraph text, without labels, bullets, bold text, or other markdown formatting.",
            "Write for end users only. Do not mention Javadoc, API, Java, methods, return values, source, or null.",
            "If raw_javadoc says null will be returned, explain that the zman may not be available or cannot be calculated in that case.",
            "Preserve useful Javadoc or HTML links from raw_javadoc as Markdown when using the linked text. Do not create new links.",
            "Keep meaning and calculation concise.",
            "Mention deprecated status only when is_deprecated is true or raw_javadoc explains deprecation.",
            "For numeric settings or offsets, say the time depends on that setting only when raw_javadoc supports it.",
            "For Kidush Levana, do not say that the zman may not be available when it does not occur on this day.",
        ],
        "output_schema": {
            "items": [
                {
                    "id": "same id as input",
                    "meaning": "plain-English meaning, source-backed",
                    "calculation": "how it is calculated, source-backed or empty",
                    "notes": ["source-backed caveats, null behavior, or settings"],
                    "deprecated_note": "source-backed warning if deprecated, otherwise empty",
                }
            ]
        },
        "items": [model_payload(entry) for entry in entries],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


async def call_model(
    client: AsyncOpenAI,
    model: str,
    seed: int,
    reasoning_effort: ReasoningEffort,
    category: str,
    entries: list[SourceEntry],
) -> tuple[dict[str, dict[str, Any]], list[str]]:
    completion = await client.chat.completions.create(
        model=model,
        seed=seed,
        reasoning_effort=reasoning_effort,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": system_prompt()},
            {"role": "user", "content": user_prompt(category, entries)},
        ],
    )
    content = completion.choices[0].message.content or ""
    try:
        parsed = json.loads(content)
    except json.JSONDecodeError as exc:
        return {}, [f"Model returned invalid JSON for {category}: {exc}"]

    output_items = parsed.get("items")
    if not isinstance(output_items, list):
        return {}, [f"Model response for {category} did not contain an items list."]

    by_id: dict[str, dict[str, Any]] = {}
    warnings: list[str] = []
    expected_ids = {entry.id for entry in entries}

    for output_item in output_items:
        if not isinstance(output_item, dict):
            warnings.append(f"Model returned a non-object item in {category}.")
            continue
        item_id = output_item.get("id")
        if not isinstance(item_id, str) or item_id not in expected_ids:
            warnings.append(
                f"Model returned an unknown item id in {category}: {item_id!r}"
            )
            continue
        by_id[item_id] = output_item

    missing_ids = sorted(expected_ids - set(by_id))
    for missing_id in missing_ids:
        warnings.append(f"Model omitted {missing_id} in {category}.")

    return by_id, warnings


async def run_batch_job(
    client: AsyncOpenAI,
    model: str,
    seed: int,
    reasoning_effort: ReasoningEffort,
    job: BatchJob,
) -> BatchResult:
    try:
        output, warnings = await call_model(
            client, model, seed, reasoning_effort, job.category, job.entries
        )
    except Exception as exc:  # OpenAI SDK exceptions vary by transport/version.
        return BatchResult(job=job, output={}, warnings=[], error=str(exc))
    return BatchResult(job=job, output=output, warnings=warnings)


async def generate_model_outputs(
    api_key: str,
    model: str,
    seed: int,
    reasoning_effort: ReasoningEffort,
    request_timeout: float,
    batch_jobs: list[BatchJob],
) -> tuple[dict[str, dict[str, Any]], list[str]]:
    generated_by_id: dict[str, dict[str, Any]] = {}
    warnings: list[str] = []
    if not batch_jobs:
        return generated_by_id, warnings

    client = AsyncOpenAI(api_key=api_key, timeout=request_timeout, max_retries=1)
    tasks = [
        asyncio.create_task(run_batch_job(client, model, seed, reasoning_effort, job))
        for job in batch_jobs
    ]

    try:
        for completed_count, completed_task in enumerate(
            asyncio.as_completed(tasks), start=1
        ):
            result = await completed_task
            print(
                f"Finished batch {completed_count}/{len(batch_jobs)}: {result.job.category} ({result.job.index})",
                flush=True,
            )
            if result.error:
                warnings.append(
                    f"OpenAI request failed for {result.job.category} batch {result.job.index}: {result.error}"
                )
                continue
            generated_by_id.update(result.output)
            warnings.extend(result.warnings)
    finally:
        await client.close()

    return generated_by_id, warnings


def markdown_escape(text: str) -> str:
    return text.replace("\r\n", "\n").strip()


def paragraph_text(text: str) -> str:
    return re.sub(r"\s+", " ", markdown_escape(text)).strip()


def should_hide_note(entry: SourceEntry, note: str) -> bool:
    normalized = note.lower().rstrip(".")
    if entry.category == "Kidush Levana" and normalized == (
        "if the zman does not occur on this day, the time may not be available"
    ):
        return True
    return False


def heading_slug(title: str) -> str:
    slug = title.lower()
    slug = re.sub(r"`([^`]*)`", r"\1", slug)
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug.strip())
    return slug or "zman"


def category_id_for_label(category_label: str) -> str:
    for category_id, label in CATEGORY_LABELS.items():
        if label == category_label:
            return category_id
    raise ValueError(f"No category id found for label {category_label!r}.")


def category_page_paths(
    groups: dict[str, list[SourceEntry]],
    generated_by_id: dict[str, dict[str, Any]],
    pages_dir: Path,
) -> dict[str, Path]:
    page_paths_by_category: dict[str, Path] = {}

    for category, entries in groups.items():
        rendered_entries = [entry for entry in entries if entry.id in generated_by_id]
        if not rendered_entries:
            continue

        category_id = category_id_for_label(category)
        page_path = pages_dir / f"{category_id}.md"
        page_paths_by_category[category] = page_path

    return page_paths_by_category


def render_item(
    entry: SourceEntry,
    generated: dict[str, Any],
) -> str:
    lines: list[str] = [f"## {entry.title}", ""]

    reference = (
        f"`{entry.class_name}.{entry.method}`"
        if entry.class_name
        else f"`{entry.method}`"
    )

    deprecated_note = paragraph_text(str(generated.get("deprecated_note") or ""))
    if entry.is_deprecated:
        warning = deprecated_note or "This zman is marked deprecated."
        lines.extend([warning, ""])

    meaning = paragraph_text(str(generated.get("meaning") or ""))
    calculation = paragraph_text(str(generated.get("calculation") or ""))
    raw_notes = generated.get("notes")
    note_values: list[Any] = raw_notes if isinstance(raw_notes, list) else []
    notes = [
        note
        for note in (paragraph_text(str(note)) for note in note_values)
        if note and not should_hide_note(entry, note)
    ]

    if meaning:
        lines.extend([meaning, ""])
    if calculation:
        lines.extend([calculation, ""])
    if notes:
        for note in notes:
            lines.extend([note, ""])

    lines.append('??? info "Technical details"')
    lines.append(f"    Source method: {reference}")
    lines.append("")
    lines.append(f"    Technical reference: `{entry.qualified_name}`")
    lines.append("")
    return "\n".join(lines)


def render_category_pages(
    groups: dict[str, list[SourceEntry]],
    generated_by_id: dict[str, dict[str, Any]],
    page_paths_by_category: dict[str, Path],
    index_filename: str,
) -> dict[Path, str]:
    pages: dict[Path, str] = {}
    for category, entries in groups.items():
        rendered_entries = [entry for entry in entries if entry.id in generated_by_id]
        if not rendered_entries:
            continue

        lines = [
            GENERATED_MARKER,
            "",
            f"# {category}",
            "",
            f"[Back to all zmanim]({index_filename})",
            "",
        ]
        for entry in rendered_entries:
            lines.append(
                render_item(
                    entry,
                    generated_by_id[entry.id],
                )
            )
        pages[page_paths_by_category[category]] = "\n".join(lines).rstrip() + "\n"
    return pages


def base_report(
    args: argparse.Namespace,
    encoding: str,
    source_count: int,
    entries: list[SourceEntry],
    groups: dict[str, list[SourceEntry]],
) -> dict[str, Any]:
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "command": args.command,
        "input": str(args.input),
        "generated_content": str(
            getattr(args, "generated_output", getattr(args, "generated", ""))
        ),
        "pages_dir": str(getattr(args, "pages_dir", "")),
        "index_link": str(getattr(args, "index_link", "")),
        "model": getattr(args, "model", None),
        "seed": getattr(args, "seed", None),
        "reasoning_effort": getattr(args, "reasoning_effort", None),
        "dry_run": bool(args.dry_run),
        "source_encoding": encoding,
        "source_entries": source_count,
        "render_entries": len(entries),
        "categories": {
            category: len(category_entries)
            for category, category_entries in groups.items()
        },
        "generated_items": 0,
        "skipped_items": [],
        "warnings": [],
    }


def generated_content_json(
    args: argparse.Namespace,
    encoding: str,
    source_count: int,
    entries: list[SourceEntry],
    groups: dict[str, list[SourceEntry]],
    generated_by_id: dict[str, dict[str, Any]],
    report: dict[str, Any],
) -> dict[str, Any]:
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "input": str(args.input),
        "model": args.model,
        "seed": args.seed,
        "reasoning_effort": args.reasoning_effort,
        "source_encoding": encoding,
        "source_entries": source_count,
        "render_entries": len(entries),
        "categories": {
            category: len(category_entries)
            for category, category_entries in groups.items()
        },
        "items": [generated_by_id[item_id] for item_id in sorted(generated_by_id)],
        "skipped_items": report["skipped_items"],
        "warnings": report["warnings"],
    }


def load_generated_content(path: Path) -> dict[str, dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    raw_items: Any
    if isinstance(data, dict):
        raw_items = data.get("items")
    else:
        raw_items = data

    if not isinstance(raw_items, list):
        raise ValueError(f"Expected an items list in {path}")

    generated_by_id: dict[str, dict[str, Any]] = {}
    for item in raw_items:
        if not isinstance(item, dict):
            continue
        item_id = item.get("id")
        if isinstance(item_id, str):
            generated_by_id[item_id] = item
    return generated_by_id


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True) if path.parent != Path(".") else None
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def write_markdown(path: Path, markdown: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_name(f"{path.name}.tmp")
    temp_path.write_text(markdown, encoding="utf-8")
    temp_path.replace(path)


def cleanup_generated_pages(pages_dir: Path) -> None:
    if not pages_dir.exists():
        return

    for path in pages_dir.glob("*.md"):
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
        except IndexError, OSError, UnicodeDecodeError:
            continue
        if first_line == GENERATED_MARKER:
            path.unlink()


def write_pages(pages: dict[Path, str]) -> None:
    for path, markdown in pages.items():
        write_markdown(path, markdown)


def add_missing_raw_skips(
    report: dict[str, Any],
    entries: list[SourceEntry],
) -> None:
    missing_raw = [entry for entry in entries if not entry.raw_javadoc]
    for entry in missing_raw:
        report["skipped_items"].append(
            {
                "id": entry.id,
                "title": entry.title,
                "reason": "No docs.raw Javadoc text was available.",
            }
        )


def print_category_summary(
    items: list[dict[str, Any]],
    entries: list[SourceEntry],
    groups: dict[str, list[SourceEntry]],
) -> None:
    print(f"Loaded {len(items)} source entries as {len(entries)} render entries.")
    for category, category_entries in groups.items():
        print(f"{category}: {len(category_entries)}")


def run_generate_json(
    args: argparse.Namespace,
    items: list[dict[str, Any]],
    encoding: str,
    entries: list[SourceEntry],
    groups: dict[str, list[SourceEntry]],
) -> int:
    report = base_report(args, encoding, len(items), entries, groups)
    add_missing_raw_skips(report, entries)

    eligible_groups = {
        category: [entry for entry in category_entries if entry.raw_javadoc]
        for category, category_entries in groups.items()
    }

    if args.dry_run:
        write_json(args.report, report)
        print_category_summary(items, entries, groups)
        print(f"Dry run report written to {args.report}")
        return 0

    api_key = openai_api_key(args.env_file)
    if not api_key:
        report["warnings"].append(
            f"No OpenAI API key found. Set OPENAI_API_KEY or add OPENAI-KEY to {args.env_file}."
        )
        write_json(args.report, report)
        print(report["warnings"][-1], file=sys.stderr)
        return 1

    generated_by_id: dict[str, dict[str, Any]] = {}
    batch_jobs: list[BatchJob] = []
    for category, category_entries in eligible_groups.items():
        for batch in batched(category_entries, args.batch_size):
            batch_jobs.append(BatchJob(len(batch_jobs) + 1, category, batch))

    total_batches = len(batch_jobs)
    print(f"Generating {total_batches} batches asynchronously...", flush=True)
    generated_by_id, generation_warnings = asyncio.run(
        generate_model_outputs(
            api_key,
            args.model,
            args.seed,
            cast(ReasoningEffort, args.reasoning_effort),
            args.request_timeout,
            batch_jobs,
        )
    )
    report["warnings"].extend(generation_warnings)

    for entry in entries:
        if entry.raw_javadoc and entry.id not in generated_by_id:
            report["skipped_items"].append(
                {
                    "id": entry.id,
                    "title": entry.title,
                    "reason": "No usable model output was returned.",
                }
            )

    report["generated_items"] = len(generated_by_id)

    if not generated_by_id:
        print(
            f"No usable content was generated; {args.generated_output} was not written.",
            file=sys.stderr,
        )
        write_json(args.report, report)
        return 1

    write_json(
        args.generated_output,
        generated_content_json(
            args,
            encoding,
            len(items),
            entries,
            groups,
            generated_by_id,
            report,
        ),
    )
    write_json(args.report, report)
    print(f"Wrote generated content to {args.generated_output}.")
    print(f"Wrote generation report to {args.report}.")
    return 0


def run_render_md(
    args: argparse.Namespace,
    items: list[dict[str, Any]],
    encoding: str,
    entries: list[SourceEntry],
    groups: dict[str, list[SourceEntry]],
) -> int:
    report = base_report(args, encoding, len(items), entries, groups)
    add_missing_raw_skips(report, entries)

    try:
        generated_by_id = load_generated_content(args.generated)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        report["warnings"].append(
            f"Could not read generated content from {args.generated}: {exc}"
        )
        write_json(args.report, report)
        print(report["warnings"][-1], file=sys.stderr)
        return 1

    source_ids = {entry.id for entry in entries}
    unknown_ids = sorted(set(generated_by_id) - source_ids)
    for item_id in unknown_ids:
        report["warnings"].append(
            f"Generated content contains unknown item id not present in {args.input}: {item_id}"
        )

    generated_by_id = {
        item_id: item
        for item_id, item in generated_by_id.items()
        if item_id in source_ids
    }
    for entry in entries:
        if entry.raw_javadoc and entry.id not in generated_by_id:
            report["skipped_items"].append(
                {
                    "id": entry.id,
                    "title": entry.title,
                    "reason": "No generated content was found.",
                }
            )

    report["generated_items"] = len(generated_by_id)

    if args.dry_run:
        write_json(args.report, report)
        print_category_summary(items, entries, groups)
        print(
            f"Loaded {len(generated_by_id)} generated content items from {args.generated}."
        )
        print(f"Dry run report written to {args.report}")
        return 0

    if not generated_by_id:
        print(
            "No usable generated content was found; category pages were not written.",
            file=sys.stderr,
        )
        write_json(args.report, report)
        return 1

    page_paths_by_category = category_page_paths(
        groups,
        generated_by_id,
        args.pages_dir,
    )
    pages = render_category_pages(
        groups,
        generated_by_id,
        page_paths_by_category,
        args.index_link,
    )

    cleanup_generated_pages(OLD_GENERATED_PAGES_DIR)
    cleanup_generated_pages(args.pages_dir)
    write_pages(pages)

    report["generated_pages"] = len(pages)
    write_json(args.report, report)
    print(f"Wrote {len(pages)} generated category pages.")
    print(f"Wrote generation report to {args.report}.")
    return 0


def main() -> int:
    args = parse_args()
    validate_category_config()
    items, encoding = load_json(args.input)
    entries = source_entries(items)
    groups = grouped_entries(entries)

    if args.command == "generate-json":
        return run_generate_json(args, items, encoding, entries, groups)
    if args.command == "render-md":
        return run_render_md(args, items, encoding, entries, groups)
    raise ValueError(f"Unknown command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
