"""Editable category assignments for generated zmanim docs.

Edit CATEGORY_LABELS to rename a category.
Edit CATEGORY_ORDER to reorder categories.
Edit ZMAN_CATEGORIES to move a zman to a different category.

Every generated zman must be listed in ZMAN_CATEGORIES unless it is listed in
EXCLUDED_ZMANIM. Missing or unknown category assignments are treated as errors.
"""

from __future__ import annotations


CATEGORY_LABELS = {
    "alos": "Alos HaShachar",
    "astronomical_dawn": "Astronomical Dawn",
    "mishayakir": "Misheyakir",
    "sunrise": "Netz HaChamah",
    "end_shema": "Sof Zman Shema",
    "end_tefilla": "Sof Zman Tefilla",
    "end_eating_chometz": "Sof Zman Achilas Chametz",
    "end_burning_chometz": "Sof Zman Biur Chametz",
    "midday": "Chatzos Hayom",
    "mincha_gedola": "Mincha Gedola",
    "mincha_ketana": "Mincha Ketana",
    "plag_mincha": "Plag Mincha",
    "sunset": "Sunset",
    "astronomical_twilight": "Astronomical Twilight",
    "midnight": "Midnight",
    "bein_hashmashos": "Bein Hashmashos",
    "tzais_geonim": "Tzais Geonim",
    "tzais": "Tzais",
    "kidush_levana": "Kidush Levana",
    "candle_lighting": "Candle Lighting",
}

CATEGORY_ORDER = [
    "alos",
    "astronomical_dawn",
    "mishayakir",
    "sunrise",
    "end_shema",
    "end_tefilla",
    "end_eating_chometz",
    "end_burning_chometz",
    "midday",
    "mincha_gedola",
    "mincha_ketana",
    "plag_mincha",
    "candle_lighting",
    "sunset",
    "bein_hashmashos",
    "tzais_geonim",
    "tzais",
    "astronomical_twilight",
    "midnight",
    "kidush_levana",
]

EXCLUDED_ZMANIM = {"getZman", "getMoladAsInstant", "getZmanMolad"}

ZMAN_CATEGORIES = {
    "getSunrise": "sunrise",
    "getSeaLevelSunrise": "sunrise",
    "getBeginCivilTwilight": "astronomical_dawn",
    "getBeginNauticalTwilight": "astronomical_dawn",
    "getBeginAstronomicalTwilight": "astronomical_dawn",
    "getSunset": "sunset",
    "getSeaLevelSunset": "sunset",
    "getEndCivilTwilight": "astronomical_twilight",
    "getEndNauticalTwilight": "astronomical_twilight",
    "getEndAstronomicalTwilight": "astronomical_twilight",
    "getSunTransit": "midday",
    "getSolarMidnight": "midnight",
    "getPlagHamincha120MinutesZmanis": "plag_mincha",
    "getPlagHamincha120Minutes": "plag_mincha",
    "getAlos60Minutes": "alos",
    "getAlos72Zmanis": "alos",
    "getAlos96Minutes": "alos",
    "getAlos90Zmanis": "alos",
    "getAlos96Zmanis": "alos",
    "getAlos90Minutes": "alos",
    "getAlos120Minutes": "alos",
    "getAlos120Zmanis": "alos",
    "getAlos26Degrees": "alos",
    "getAlos18Degrees": "alos",
    "getAlos19Degrees": "alos",
    "getAlos19Point8Degrees": "alos",
    "getMisheyakir12Point85Degrees": "mishayakir",
    "getMisheyakir11Point5Degrees": "mishayakir",
    "getMisheyakir11Degrees": "mishayakir",
    "getMisheyakir10Point2Degrees": "mishayakir",
    "getMisheyakir7Point65Degrees": "mishayakir",
    "getMisheyakir9Point5Degrees": "mishayakir",
    "getSofZmanShmaMGA19Point8Degrees": "end_shema",
    "getSofZmanShmaMGA16Point1Degrees": "end_shema",
    "getSofZmanShmaMGA18Degrees": "end_shema",
    "getSofZmanShmaMGA72MinutesZmanis": "end_shema",
    "getSofZmanShmaMGA90Minutes": "end_shema",
    "getSofZmanShmaMGA90MinutesZmanis": "end_shema",
    "getSofZmanShmaMGA96Minutes": "end_shema",
    "getSofZmanShmaMGA96MinutesZmanis": "end_shema",
    "getSofZmanShma3HoursBeforeChatzos": "end_shema",
    "getSofZmanShmaMGA120Minutes": "end_shema",
    "getSofZmanShmaAlos16Point1ToSunset": "end_shema",
    "getSofZmanShmaAlos16Point1ToTzaisGeonim7Point083Degrees": "end_shema",
    "getSofZmanTfilaMGA19Point8Degrees": "end_tefilla",
    "getSofZmanTfilaMGA16Point1Degrees": "end_tefilla",
    "getSofZmanTfilaMGA18Degrees": "end_tefilla",
    "getSofZmanTfilaMGA72MinutesZmanis": "end_tefilla",
    "getSofZmanTfilaMGA90Minutes": "end_tefilla",
    "getSofZmanTfilaMGA90MinutesZmanis": "end_tefilla",
    "getSofZmanTfilaMGA96Minutes": "end_tefilla",
    "getSofZmanTfilaMGA96MinutesZmanis": "end_tefilla",
    "getSofZmanTfilaMGA120Minutes": "end_tefilla",
    "getSofZmanTfila2HoursBeforeChatzos": "end_tefilla",
    "getMinchaGedola30Minutes": "mincha_gedola",
    "getMinchaGedola72Minutes": "mincha_gedola",
    "getMinchaGedola16Point1Degrees": "mincha_gedola",
    "getMinchaGedolaAhavatShalom": "mincha_gedola",
    "getMinchaGedolaGRAGreaterThan30": "mincha_gedola",
    "getMinchaKetana16Point1Degrees": "mincha_ketana",
    "getMinchaKetanaAhavatShalom": "mincha_ketana",
    "getMinchaKetana72Minutes": "mincha_ketana",
    "getPlagHamincha60Minutes": "plag_mincha",
    "getPlagHamincha72Minutes": "plag_mincha",
    "getPlagHamincha90Minutes": "plag_mincha",
    "getPlagHamincha96Minutes": "plag_mincha",
    "getPlagHamincha96MinutesZmanis": "plag_mincha",
    "getPlagHamincha90MinutesZmanis": "plag_mincha",
    "getPlagHamincha72MinutesZmanis": "plag_mincha",
    "getPlagHamincha16Point1Degrees": "plag_mincha",
    "getPlagHamincha19Point8Degrees": "plag_mincha",
    "getPlagHamincha26Degrees": "plag_mincha",
    "getPlagHamincha18Degrees": "plag_mincha",
    "getPlagAlosToSunset": "plag_mincha",
    "getPlagAlos16Point1ToTzaisGeonim7Point083Degrees": "plag_mincha",
    "getPlagAhavatShalom": "plag_mincha",
    "getBainHashmashosRT13Point24Degrees": "bein_hashmashos",
    "getBainHashmashosRT58Point5Minutes": "bein_hashmashos",
    "getBainHashmashosRT13Point5MinutesBefore7Point083Degrees": "bein_hashmashos",
    "getBainHashmashosRT2Stars": "bein_hashmashos",
    "getBainHashmashosYereim18Minutes": "bein_hashmashos",
    "getBainHashmashosYereim3Point05Degrees": "bein_hashmashos",
    "getBainHashmashosYereim16Point875Minutes": "bein_hashmashos",
    "getBainHashmashosYereim2Point8Degrees": "bein_hashmashos",
    "getBainHashmashosYereim13Point5Minutes": "bein_hashmashos",
    "getBainHashmashosYereim2Point1Degrees": "bein_hashmashos",
    "getTzaisGeonim3Point7Degrees": "tzais_geonim",
    "getTzaisGeonim3Point8Degrees": "tzais_geonim",
    "getTzaisGeonim5Point95Degrees": "tzais_geonim",
    "getTzaisGeonim4Point66Degrees": "tzais_geonim",
    "getTzaisGeonim4Point42Degrees": "tzais_geonim",
    "getTzaisGeonim4Point8Degrees": "tzais_geonim",
    "getTzaisGeonim6Point45Degrees": "tzais_geonim",
    "getTzaisGeonim7Point083Degrees": "tzais_geonim",
    "getTzaisGeonim7Point67Degrees": "tzais_geonim",
    "getTzaisGeonim9Point3Degrees": "tzais_geonim",
    "getTzaisGeonim9Point75Degrees": "tzais_geonim",
    "getTzais60Minutes": "tzais",
    "getTzaisAteretTorah": "tzais",
    "getSofZmanShmaAteretTorah": "end_shema",
    "getSofZmanTfilaAteretTorah": "end_tefilla",
    "getMinchaGedolaAteretTorah": "mincha_gedola",
    "getMinchaKetanaAteretTorah": "mincha_ketana",
    "getPlagHaminchaAteretTorah": "plag_mincha",
    "getTzais72Zmanis": "tzais",
    "getTzais90Zmanis": "tzais",
    "getTzais96Zmanis": "tzais",
    "getTzais90Minutes": "tzais",
    "getTzais120Minutes": "tzais",
    "getTzais120Zmanis": "tzais",
    "getTzais16Point1Degrees": "tzais",
    "getTzais26Degrees": "tzais",
    "getTzais18Degrees": "tzais",
    "getTzais19Point8Degrees": "tzais",
    "getTzais96Minutes": "tzais",
    "getFixedLocalChatzosHayom": "midday",
    "getSofZmanKidushLevanaBetweenMoldos": "kidush_levana",
    "getSofZmanKidushLevana15Days": "kidush_levana",
    "getTchilasZmanKidushLevana3Days": "kidush_levana",
    "getTchilasZmanKidushLevana7Days": "kidush_levana",
    "getSofZmanAchilasChametzGRA": "end_eating_chometz",
    "getSofZmanAchilasChametzMGA72Minutes": "end_eating_chometz",
    "getSofZmanAchilasChametzMGA72MinutesZmanis": "end_eating_chometz",
    "getSofZmanAchilasChametzMGA16Point1Degrees": "end_eating_chometz",
    "getSofZmanBiurChametzGRA": "end_burning_chometz",
    "getSofZmanBiurChametzMGA72Minutes": "end_burning_chometz",
    "getSofZmanBiurChametzMGA72MinutesZmanis": "end_burning_chometz",
    "getSofZmanBiurChametzMGA16Point1Degrees": "end_burning_chometz",
    "getAlosBaalHatanya": "alos",
    "getSofZmanShmaBaalHatanya": "end_shema",
    "getSofZmanTfilaBaalHatanya": "end_tefilla",
    "getSofZmanAchilasChametzBaalHatanya": "end_eating_chometz",
    "getSofZmanBiurChametzBaalHatanya": "end_burning_chometz",
    "getMinchaGedolaBaalHatanya": "mincha_gedola",
    "getMinchaKetanaBaalHatanya": "mincha_ketana",
    "getPlagHaminchaBaalHatanya": "plag_mincha",
    "getTzaisBaalHatanya": "tzais",
    "getSofZmanShmaMGA18DegreesToFixedLocalChatzos": "end_shema",
    "getSofZmanShmaMGA16Point1DegreesToFixedLocalChatzos": "end_shema",
    "getSofZmanShmaMGA90MinutesToFixedLocalChatzos": "end_shema",
    "getSofZmanShmaMGA72MinutesToFixedLocalChatzos": "end_shema",
    "getSofZmanShmaGRASunriseToFixedLocalChatzos": "end_shema",
    "getSofZmanTfilaGRASunriseToFixedLocalChatzos": "end_tefilla",
    "getMinchaGedolaGRAFixedLocalChatzos30Minutes": "mincha_gedola",
    "getMinchaKetanaGRAFixedLocalChatzosToSunset": "mincha_ketana",
    "getPlagHaminchaGRAFixedLocalChatzosToSunset": "plag_mincha",
    "getTzais50Minutes": "tzais",
    "getSamuchLeMinchaKetanaGRA": "mincha_ketana",
    "getSamuchLeMinchaKetana16Point1Degrees": "mincha_ketana",
    "getSamuchLeMinchaKetana72Minutes": "mincha_ketana",
    "getSunsetOrWesternmostSolarAzimuth": "sunset",
    "getSunriseOrEasternmostSolarAzimuth": "sunrise",
    "getTzaisGeonim8Point5Degrees": "tzais_geonim",
    "getAlos16Point1Degrees": "alos",
    "getAlos72Minutes": "alos",
    "getChatzosHayom": "midday",
    "getChatzosHalayla": "midnight",
    "getChatzosHayomAsHalfDay": "midday",
    "getSofZmanShmaGRA": "end_shema",
    "getSofZmanShmaMGA72Minutes": "end_shema",
    "getTzais72Minutes": "tzais",
    "getCandleLighting": "candle_lighting",
    "getSofZmanTfilaGRA": "end_tefilla",
    "getSofZmanTfilaMGA72Minutes": "end_tefilla",
    "getMinchaGedolaGRA": "mincha_gedola",
    "getMinchaKetanaGRA": "mincha_ketana",
    "getPlagHaminchaGRA": "plag_mincha",
}
